---
#Project Info
title: "Regex"
author: "Rain Zhu"
date: "05/02/2021"
output: html_document
---
[Rain's Github](https://github.com/JazzyRain/BIOL432/)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)## knitr setup
library(knitr)## This function allows us to use kable()
```

## Data setup

```{r}
MData<-read.csv("./InputData/measurements.csv",header=T) #import data and set object as MData
library(dplyr)#load dplyr

```

## Creation of "Sp" Column

Adding a new column called sp with dplyr command and shorten the genus name in Organism column to show only the first letter and period with regex

```{r}
MData<-mutate(MData, Sp=sub("(\\w)\\w+","\\1.",MData$Organism))
##In MData, I used mutate to setup a new column called sp. 
##values from sp are taken from "Organism".(\\w)\\w+ is capturing the first letter of an entire word. the sub function lets me to act only on the first word. \\1. is outputting the first capture which is (\\w) hence, the first letter + "." and the rest of the string (the species name)

kable(MData)# show MyData with kaple function for neater look 
```
## Organism-> Sp
Use dplyr to create a new dataset with Sp replacing the Organism column and moved to the beginning in place of the original organism column
```{r}
MData<-select(MData,Sp, Limb.width, Limb.length, Observer) ##using select() I got rid of "Organism" and sorted all columns in the desired arrangement
kable(MData)##output MData with kable() for neater look
```
## Save dataset
```{r}
write.csv(MData,"./Output/MeasShort.csv")#save new csv file in the Output folder
```









